### ISSUE TITLE
Got ClientConnectorCertificateError while trying to access https://alpha4.starknet.io/gateway/add_transaction

### ISSUE THREAD

**Issue by qkaver** [l-henri/starknet-erc721#18]
Got ClientConnectorCertificateError while trying to access https://alpha4.starknet.io/gateway/add_transaction.
Traceback (most recent call last):
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/services/external_api/client.py", line 116, in _send_request
    async with session.request(
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host alpha4.starknet.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Error: ClientConnectorCertificateError: Cannot connect to host alpha4.starknet.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Traceback (most recent call last):
  File "/Users/qkaver/starknet/env/bin/nile", line 8, in <module>
    sys.exit(cli())
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/nile/cli.py", line 85, in deploy
    deploy_command(artifact, arguments, network, alias)
  File "/Users/qkaver/starknet/env/lib/python3.8/site-packages/nile/core/deploy.py", line 34, in deploy
    output = subprocess.check_output(command)
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/qkaver/opt/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['starknet', 'deploy', '--contract', 'artifacts/ERC721.json', '--inputs', '6001127147006152263', '21336', '2689760648704244976701818254133193310968075258309729491871695171359883455256']' returned non-zero exit status 1.

**Comment by l-henri** [comment]
Thank you! 
This looks like an issue with your wallet. Can you please send it on the reference of the repo, https://github.com/starknet-edu/starknet-cairo-101 ?
Thank you,
